[package]
name = "sc-chain-spec"
version = "4.0.0-dev"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = ""
repository = "https://github.com/axia-tech/axia-core/"
description = "Axlib chain configurations."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sc-chain-spec-derive = { version = "4.0.0-dev", path = "./derive" }
impl-trait-for-tuples = "0.2.1"
sc-network = { version = "0.10.0-dev", path = "../network" }
sp-core = { version = "4.0.0-dev", path = "../../primitives/core" }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.68"
sp-runtime = { version = "4.0.0-dev", path = "../../primitives/runtime" }
sc-telemetry = { version = "4.0.0-dev", path = "../telemetry" }
codec = { git = "https://github.com/axia-tech/axia-scale-codec", package = "axia-scale-codec", branch = "v2.3.1" }
