[package]
name = "sp-keyring"
version = "4.0.0-dev"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"
license = "Apache-2.0"
homepage = ""
repository = "https://github.com/axia-tech/axia-core/"
description = "Keyring support code for the runtime. A set of test accounts."
documentation = "https://docs.rs/sp-keyring"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
sp-core = { version = "4.0.0-dev", path = "../core" }
sp-runtime = { version = "4.0.0-dev", path = "../runtime" }
lazy_static = "1.4.0"
strum = { version = "0.20.0", features = ["derive"] }
