[package]
name = "axlib-frame-rpc-support"
version = "3.0.0"
authors = [
    "AXIA Technologies <admin@axiacoin.network>",
    "Andrew Dirksen <andrew@dirksen.com>",
]
edition = "2018"
license = "Apache-2.0"
homepage = ""
repository = "https://github.com/axia-tech/axia-core/"
description = "Axlib RPC for FRAME's support"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.16"
jsonrpc-client-transports = { git = "https://github.com/axia-tech/jsonrpc", branch = "master", version = "18.0.0", features = ["http"] }
codec = { git = "https://github.com/axia-tech/axia-scale-codec", package = "axia-scale-codec", branch = "v2.3.1" }
serde = "1"
frame-support = { version = "4.0.0-dev", path = "../../../../frame/support" }
sp-storage = { version = "4.0.0-dev", path = "../../../../primitives/storage" }
sc-rpc-api = { version = "0.10.0-dev", path = "../../../../client/rpc-api" }

[dev-dependencies]
frame-system = { version = "4.0.0-dev", path = "../../../../frame/system" }
scale-info = { git = "https://github.com/axia-tech/scale-info", branch = "v1.0.0" }
tokio = "1.10"
