[package]
name = "sc-consensus-manual-seal"
version = "0.10.0-dev"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
description = "Manual sealing engine for Axlib"
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = ""
repository = "https://github.com/axia-tech/axia-core/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
derive_more = "0.99.2"
futures = "0.3.9"
jsonrpc-core = { git = "https://github.com/axia-tech/jsonrpc", branch = "master", version = "18.0.0" }
jsonrpc-core-client = { git = "https://github.com/axia-tech/jsonrpc", branch = "master", version = "18.0.0" }
jsonrpc-derive = { git = "https://github.com/axia-tech/jsonrpc", branch = "master", version = "18.0.0" }
log = "0.4.8"
codec = { git = "https://github.com/axia-tech/axia-scale-codec", package = "axia-scale-codec", branch = "v2.3.1" }
serde = { version = "1.0", features = ["derive"] }
assert_matches = "1.3.0"
async-trait = "0.1.50"

sc-client-api = { path = "../../api", version = "4.0.0-dev" }
sc-consensus = { version = "0.10.0-dev", path = "../../consensus/common" }
sc-consensus-babe = { path = "../../consensus/babe", version = "0.10.0-dev" }
sc-consensus-epochs = { path = "../../consensus/epochs", version = "0.10.0-dev" }
sp-consensus-babe = { path = "../../../primitives/consensus/babe", version = "0.10.0-dev" }

sc-transaction-pool = { path = "../../transaction-pool", version = "4.0.0-dev" }
sp-blockchain = { path = "../../../primitives/blockchain", version = "4.0.0-dev" }
sp-consensus = { path = "../../../primitives/consensus/common", version = "0.10.0-dev" }
sp-consensus-slots = { path = "../../../primitives/consensus/slots", version = "0.10.0-dev" }
sp-inherents = { path = "../../../primitives/inherents", version = "4.0.0-dev" }
sp-runtime = { path = "../../../primitives/runtime", version = "4.0.0-dev" }
sp-core = { path = "../../../primitives/core", version = "4.0.0-dev" }
sp-keystore = { path = "../../../primitives/keystore", version = "0.10.0-dev" }
sp-api = { path = "../../../primitives/api", version = "4.0.0-dev" }
sc-transaction-pool-api = { path = "../../../client/transaction-pool/api", version = "4.0.0-dev" }
sp-timestamp = { path = "../../../primitives/timestamp", version = "4.0.0-dev" }

prometheus-endpoint = { package = "axlib-prometheus-endpoint", path = "../../../utils/prometheus", version = "0.9.0" }

[dev-dependencies]
tokio = { version = "1.10.0", features = ["rt-multi-thread", "macros"] }
sc-basic-authorship = { path = "../../basic-authorship", version = "0.10.0-dev" }
axlib-test-runtime-client = { path = "../../../test-utils/runtime/client", version = "2.0.0" }
axlib-test-runtime-transaction-pool = { path = "../../../test-utils/runtime/transaction-pool", version = "2.0.0" }
