[package]
name = "sp-authorship"
version = "4.0.0-dev"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
description = "Authorship primitives"
edition = "2018"
license = "Apache-2.0"
homepage = ""
repository = "https://github.com/axia-tech/axia-core/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-inherents = { version = "4.0.0-dev", default-features = false, path = "../inherents" }
sp-runtime = { version = "4.0.0-dev", default-features = false, path = "../runtime" }
sp-std = { version = "4.0.0-dev", default-features = false, path = "../std" }
codec = { git = "https://github.com/axia-tech/axia-scale-codec", package = "axia-scale-codec", branch = "v2.3.1", default-features = false, features = ["derive"] }
async-trait = { version = "0.1.50", optional = true }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"sp-std/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"async-trait",
]
