[package]
name = "sp-version-proc-macro"
version = "4.0.0-dev"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"
license = "Apache-2.0"
homepage = ""
repository = "https://github.com/axia-tech/axia-core/"
description = "Macro for defining a runtime version."
documentation = "https://docs.rs/sp-api-proc-macro"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0.10"
syn = { version = "1.0.80", features = ["full", "fold", "extra-traits", "visit"] }
proc-macro2 = "1.0.29"
codec = { git = "https://github.com/axia-tech/axia-scale-codec", package = "axia-scale-codec", branch = "v2.3.1", features = [ "derive" ] }

[dev-dependencies]
sp-version = { version = "4.0.0-dev", path = ".." }
