[package]
name = "sp-consensus-pow"
version = "0.10.0-dev"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
description = "Primitives for Aura consensus"
edition = "2018"
license = "Apache-2.0"
homepage = ""
repository = "https://github.com/axia-tech/axia-core/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api = { version = "4.0.0-dev", default-features = false, path = "../../api" }
sp-std = { version = "4.0.0-dev", default-features = false, path = "../../std" }
sp-runtime = { version = "4.0.0-dev", default-features = false, path = "../../runtime" }
sp-core = { version = "4.0.0-dev", default-features = false, path = "../../core" }
codec = { git = "https://github.com/axia-tech/axia-scale-codec", package = "axia-scale-codec", branch = "v2.3.1", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = [
	"sp-std/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-core/std",
	"codec/std",
]
