[package]
name = "axlib-test-runtime-client"
version = "2.0.0"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"
license = "Apache-2.0"
homepage = ""
repository = "https://github.com/axia-tech/axia-core/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sc-light = { version = "4.0.0-dev", path = "../../../client/light" }
sp-consensus = { version = "0.10.0-dev", path = "../../../primitives/consensus/common" }
sc-consensus = { version = "0.10.0-dev", path = "../../../client/consensus/common" }
sc-block-builder = { version = "0.10.0-dev", path = "../../../client/block-builder" }
axlib-test-client = { version = "2.0.0", path = "../../client" }
sp-core = { version = "4.0.0-dev", path = "../../../primitives/core" }
axlib-test-runtime = { version = "2.0.0", path = "../../runtime" }
sp-runtime = { version = "4.0.0-dev", path = "../../../primitives/runtime" }
sp-api = { version = "4.0.0-dev", path = "../../../primitives/api" }
sp-blockchain = { version = "4.0.0-dev", path = "../../../primitives/blockchain" }
codec = { git = "https://github.com/axia-tech/axia-scale-codec", package = "axia-scale-codec", branch = "v2.3.1" }
sc-client-api = { version = "4.0.0-dev", path = "../../../client/api" }
futures = "0.3.9"
