[package]
name = "sp-consensus-vrf"
version = "0.10.0-dev"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
description = "Primitives for VRF based consensus"
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/axia-tech/axia-core/"
homepage = ""
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { git = "https://github.com/axia-tech/axia-scale-codec", package = "axia-scale-codec", branch = "v2.3.1", default-features = false }
schnorrkel = { version = "0.9.1", features = ["preaudit_deprecated", "u64_backend"], default-features = false }
sp-std = { version = "4.0.0-dev", path = "../../std", default-features = false }
sp-core = { version = "4.0.0-dev", path = "../../core", default-features = false }
sp-runtime = { version = "4.0.0-dev", default-features = false, path = "../../runtime" }

[features]
default = ["std"]
std = [
	"codec/std",
	"schnorrkel/std",
	"sp-std/std",
	"sp-core/std",
	"sp-runtime/std",
]
