[package]
name = "sp-block-builder"
version = "4.0.0-dev"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"
license = "Apache-2.0"
homepage = ""
repository = "https://github.com/axia-tech/axia-core/"
description = "The block builder runtime api."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-runtime = { version = "4.0.0-dev", default-features = false, path = "../runtime" }
sp-api = { version = "4.0.0-dev", default-features = false, path = "../api" }
sp-std = { version = "4.0.0-dev", default-features = false, path = "../std" }
codec = { git = "https://github.com/axia-tech/axia-scale-codec", package = "axia-scale-codec", branch = "v2.3.1", default-features = false }
sp-inherents = { version = "4.0.0-dev", default-features = false, path = "../inherents" }

[features]
default = [ "std" ]
std = [
	"sp-runtime/std",
	"codec/std",
	"sp-inherents/std",
	"sp-api/std",
	"sp-std/std",
]
