[package]
name = "pallet-contracts-rpc-runtime-api"
version = "4.0.0-dev"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"
license = "Apache-2.0"
homepage = ""
repository = "https://github.com/axia-tech/axia-core/"
description = "Runtime API definition required by Contracts RPC extensions."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { git = "https://github.com/axia-tech/axia-scale-codec", branch =  "v2.3.1", package = "axia-scale-codec", version = "2.3.1", default-features = false, features = ["derive"] }
scale-info = { git = "https://github.com/axia-tech/scale-info", branch = "v1.0.0", default-features = false, features = ["derive"] }

# Axlib Dependencies
pallet-contracts-primitives = { version = "4.0.0-dev", default-features = false, path = "../../common" }
sp-api = { version = "4.0.0-dev", default-features = false, path = "../../../../primitives/api" }
sp-runtime = { version = "4.0.0-dev", default-features = false, path = "../../../../primitives/runtime" }
sp-std = { version = "4.0.0-dev", default-features = false, path = "../../../../primitives/std" }

[features]
default = ["std"]
std = [
	"sp-api/std",
	"codec/std",
	"scale-info/std",
	"sp-std/std",
	"sp-runtime/std",
	"pallet-contracts-primitives/std",
]
