[package]
name = "sp-storage"
version = "4.0.0-dev"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"
description = "Storage related primitives"
license = "Apache-2.0"
homepage = ""
repository = "https://github.com/axia-tech/axia-core/"
documentation = "https://docs.rs/sp-storage/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-std = { version = "4.0.0-dev", default-features = false, path = "../std" }
serde = { version = "1.0.126", optional = true, features = ["derive"] }
impl-serde = { version = "0.3.1", optional = true }
ref-cast = "1.0.0"
sp-debug-derive = { version = "3.0.0", default-features = false, path = "../debug-derive" }
codec = { git = "https://github.com/axia-tech/axia-scale-codec", package = "axia-scale-codec", branch = "v2.3.1", default-features = false, features = ["derive"] }

[features]
default = [ "std" ]
std = [ "sp-std/std", "serde", "impl-serde", "codec/std", "sp-debug-derive/std" ]
