[package]
name = "axlib-frame-cli"
version = "4.0.0-dev"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"
license = "Apache-2.0"
homepage = ""
repository = "https://github.com/axia-tech/axia-core/"
description = "cli interface for FRAME"
documentation = "https://docs.rs/axlib-frame-cli"
readme = "README.md"

[dependencies]
sp-core = { version = "4.0.0-dev", path = "../../../primitives/core" }
sc-cli = { version = "0.10.0-dev", path = "../../../client/cli" }
sp-runtime = { version = "4.0.0-dev", path = "../../../primitives/runtime" }
structopt = "0.3.8"
frame-system = { version = "4.0.0-dev", path = "../../../frame/system" }
frame-support = { version = "4.0.0-dev", path = "../../../frame/support" }

[dev-dependencies]

[features]
default = []
