[package]
name = "sp-consensus-babe"
version = "0.10.0-dev"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
description = "Primitives for BABE consensus"
edition = "2018"
license = "Apache-2.0"
homepage = ""
repository = "https://github.com/axia-tech/axia-core/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-application-crypto = { version = "4.0.0-dev", default-features = false, path = "../../application-crypto" }
codec = { git = "https://github.com/axia-tech/axia-scale-codec", package = "axia-scale-codec", branch = "v2.3.1", default-features = false }
scale-info = { git = "https://github.com/axia-tech/scale-info", branch = "v1.0.0", default-features = false, features = ["derive"] }
merlin = { version = "2.0", default-features = false }
sp-std = { version = "4.0.0-dev", default-features = false, path = "../../std" }
sp-api = { version = "4.0.0-dev", default-features = false, path = "../../api" }
sp-consensus = { version = "0.10.0-dev", optional = true, path = "../common" }
sp-consensus-slots = { version = "0.10.0-dev", default-features = false, path = "../slots" }
sp-consensus-vrf = { version = "0.10.0-dev", path = "../vrf", default-features = false }
sp-core = { version = "4.0.0-dev", default-features = false, path = "../../core" }
sp-inherents = { version = "4.0.0-dev", default-features = false, path = "../../inherents" }
sp-keystore = { version = "0.10.0-dev", default-features = false, path = "../../keystore", optional = true }
sp-runtime = { version = "4.0.0-dev", default-features = false, path = "../../runtime" }
sp-timestamp = { version = "4.0.0-dev", path = "../../timestamp", optional = true }
serde = { version = "1.0.126", features = ["derive"], optional = true }
async-trait = { version = "0.1.50", optional = true }

[features]
default = ["std"]
std = [
	"sp-application-crypto/std",
	"codec/std",
	"scale-info/std",
	"merlin/std",
	"sp-std/std",
	"sp-api/std",
	"sp-consensus",
	"sp-consensus-slots/std",
	"sp-consensus-vrf/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-keystore",
	"sp-runtime/std",
	"serde",
	"sp-timestamp",
	"async-trait",
]
