[package]
name = 'pallet-template'
version = "3.0.0"
description = "FRAME pallet template for defining custom runtime logic."
authors = ['Axlib DevHub <https://github.com/axlib-developer-hub>']
homepage = "https://axlib.io/"
edition = '2018'
license = "Unlicense"
publish = false
repository = "https://github.com/axlib-developer-hub/axlib-node-template/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { git = "https://github.com/axia-tech/axia-scale-codec", package = "axia-scale-codec", branch = "v2.3.1", default-features = false, features = [
	"derive",
] }
scale-info = { git = "https://github.com/axia-tech/scale-info", branch = "v1.0.0", default-features = false, features = ["derive"] }
frame-support = { default-features = false, version = "4.0.0-dev", path = "../../../../frame/support" }
frame-system = { default-features = false, version = "4.0.0-dev", path = "../../../../frame/system" }
frame-benchmarking = { default-features = false, version = "4.0.0-dev", path = "../../../../frame/benchmarking", optional = true }

[dev-dependencies]
sp-core = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/core" }
sp-io = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/io" }
sp-runtime = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/runtime" }

[features]
default = ['std']
std = [
	'codec/std',
	'scale-info/std',
	'frame-support/std',
	'frame-system/std',
	'frame-benchmarking/std',
]

runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]
