[package]
name = "sc-executor-common"
version = "0.10.0-dev"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = ""
repository = "https://github.com/axia-tech/axia-core/"
description = "A set of common definitions that are needed for defining execution engines."
documentation = "https://docs.rs/sc-executor-common/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
derive_more = "0.99.2"
pwasm-utils = { git = "https://github.com/axia-tech/wasm-utils", branch = "v0.19.0", version = "0.19.0" }

codec = { git = "https://github.com/axia-tech/axia-scale-codec", package = "axia-scale-codec", branch = "v2.3.1" }
wasmi = { git = "https://github.com/axia-tech/wasmi", branch = "v0.9.1", version = "0.9.1" }
sp-core = { version = "4.0.0-dev", path = "../../../primitives/core" }
sc-allocator = { version = "4.0.0-dev", path = "../../allocator" }
sp-wasm-interface = { version = "4.0.0-dev", path = "../../../primitives/wasm-interface" }
sp-maybe-compressed-blob = { version = "4.0.0-dev", path = "../../../primitives/maybe-compressed-blob" }
sp-serializer = { version = "3.0.0", path = "../../../primitives/serializer" }
thiserror = "1.0.21"
environmental = "1.1.3"

wasmer = { version = "1.0", optional = true }
wasmer-compiler-singlepass = { version = "1.0", optional = true }

[features]
default = []
wasmer-sandbox = [
	"wasmer",
	"wasmer-compiler-singlepass",
]
